treasure-data/chef-td-agent

recipes/default.rb
This PR change platform to platform_family, this will save time for future refactoring default recipe and add new distributions. For example,  platform_family 'rhel' include centos / amazon / parallels servers and other rhel/rpm based distributes.
=> change platform to platform_family

recipes/default.rb
retrieve the gpg public key via https to prevent MITM attacks.
=> retrieve gpg signing key via https

attributes/default.rb, recipes/default.rb
A very simple PR which should fix issue #53.
As explained by @rmoriz in the original issue, default installations of ubuntu 14.04 are multiarch (with `amd64` the native architecture and `i386` the foreign architecture); adding the td-agent repository without specifying the arch breaks `apt-get update` because apt expects the repository to support both arches (amd64 and i386) while the repository only provides amd64 packages (as can be seen here: https://td-agent-package-browser.herokuapp.com/2/ubuntu/trusty/pool/contrib/t/td-agent )
The solution is simply to declare the td-agent repository as only supporting the `amd64` architecture.
=> Specify arch='amd64' to the apt_repository resource, fixing #53.

attributes/default.rb, recipes/default.rb
This change allows a wrapper cookbook to specify a local template for their own custom config.
Also delay the reload action so that a wrapper which is installing conf.d configs can also notify process and it reloads a single time.
=> Allow a wrapper cookbook to specify a local template, delay reloading the main process

recipes/default.rb, templates/default/td-agent.conf.erb
If node["td_agent"]["includes"] == true
- v1 td-agent.conf `include`
- v2 td-agent.conf `@include`
- to avoid warn log in td-agent.log
=> Use @include directive when use v2

attributes/default.rb, recipes/default.rb
Allow older Amazon Linux users to override `$releasever` at their own risk. I think this can be a workaround for situation like #60.
@repeatedly how do you think?
=> Add `yum_amazon_releasever` to override `$releasever` of yum source URL

providers/match.rb, templates/default/match.conf.erb
Insert indent space to match provider.
Example.
```
<match webserver.*>
type copy
<store>
type gelf
host 127.0.0.1
port 12201
flush_interval 5s
</store>
<store>
type stdout
</store>
</match>
```
to
```
<match webserver.*>
type copy
<store>
type gelf
host 127.0.0.1
port 12201
flush_interval 5s
</store>
<store>
type stdout
</store>
</match>
```
=> Make match definition file readable.

attributes/default.rb, recipes/default.rb
Currently, the cookbook has the user and group 'td-agent' as a hard-coded value in a couple of resource blocks. This change refactors the constant values and defines the user & group as attributes instead.
This will help us with our situation described in issue #78
=> Make system user & group as attributes

recipes/default.rb
This PR adds in support for using the CentOS 7 repo for Fedora. I have tested this on Fedora 24. 
Since Fedora is considered it's own platform family per https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/platform.rb#L191-L194 I added in a case to handle creating the repo file using the CentOS 7 repo. 
It would be super sweet if TD created an official Fedora repository. If you folks don't want to officially support Fedora and you can point me at the current CentOS 7 spec file, I can make one for Fedora and throw it on https://copr.fedorainfracloud.org/
=> Add Fedora support.

recipes/default.rb
On occasion the package install fails due to the yum mirror being unavailable:
```shell
Aug 20 03:21:38 host-007e8a9e6e94d4737 host-configure[345]: Error executing action `install` on resource 'yum_package[td-agent]'
Aug 20 03:21:38 host-007e8a9e6e94d4737 host-configure[345]: yum-deprecated -d0 -e0 -y install td-agent-2.3.2-0.el7 returned 1:
Aug 20 03:21:38 host-007e8a9e6e94d4737 host-configure[345]:   td-agent-2.3.2-0.el7.x86_64: [Errno 256] No more mirrors to try.
```
so this PR adds a retry that tries up to 3 times with a 10 second delay.
=> Add package retry

recipes/default.rb
I used Chef 12.17.44.
The following warning occurred after execution.
```
Deprecated features used!
supports { manage_home: true } on the user resource is deprecated and will be removed in Chef 13, set manage_home true instead at 1 location:
- /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/td-agent/recipes/default.rb:26:in `block in from_file'
See https://docs.chef.io/deprecations_supports_property.html for further details.
```
`manage_home` property is exists in Chef 11.0.
https://docs.chef.io/release/11-0/resource_user.html
=> Fix deprecation

recipes/default.rb, recipes/install.rb
We have some infrastructures that controls the configuration changes outside of Chef server.
Splitting install.rb from default.rb allows a wrapper cookbook only to install/upgrade td-agent, which improves this cookbook's modularity.
=> Allow wrapper cookbooks only to install td-agent

README.md, providers/filter.rb, providers/match.rb, providers/source.rb, resources/filter.rb, resources/match.rb, resources/source.rb, templates/default/filter.conf.erb, templates/default/match.conf.erb, templates/default/source.conf.erb, test/fixtures/smoke/recipes/default.rb
This is a fix to be able to run the cookbook in chef v13
Here is the error output from chef-client v13:
```
================================================================================
Recipe Compile Error in /var/cache/chef/cookbooks/td-agent/resources/filter.rb
================================================================================
ArgumentError
-------------
Property `params` of resource `td_agent_filter` overwrites an existing method.
Cookbook Trace:
---------------
/var/cache/chef/cookbooks/td-agent/resources/filter.rb:28:in `class_from_file'
```
This is a breaking change in a way, everyone using the provider need to substitute params with parameters.
=> renamed params to parameters to support chef v13

recipes/install.rb
I'd like to use `td-agent` version `3` in my environment. Setting `[td-agent][version] = 3`  isn't working for centos. 
I've added the major version in the repo url, similarly to debian platform, and it's installing version 3 now.
=> Adding major version to redhat yum repo

recipes/install.rb
Fixed support for Amazon Linux platform family in Chef 13.
13.2.20
```
* yum_package[td-agent] action upgrade
* No candidate version available for td-agent
* No candidate version available for td-agent
* No candidate version available for td-agent
* No candidate version available for td-agent
================================================================================
Error executing action `upgrade` on resource 'yum_package[td-agent]'
================================================================================
Chef::Exceptions::Package
-------------------------
No candidate version available for td-agent
Resource Declaration:
---------------------
116: package "td-agent" do
117:   retries 3
118:   retry_delay 10
119:   if node["td_agent"]["pinning_version"]
120:     action …
```
=> Fix support for Amazon Linux in install

providers/filter.rb, providers/match.rb, providers/source.rb, resources/filter.rb, resources/match.rb, resources/source.rb, test/fixtures/smoke/recipes/default.rb
Workarounds for incompatible changes of #93 for Chef pre-13.x. This restores the old `params` property on pre-13.x and show some deprecation warnings on the usage.
=> Make sure `params` is still available on Chef 12.x

recipes/default.rb
I've adjusted the setup recipe to re-order the installation of the custom plugins and then restart the agent. 
This will resolve a bug where any plugins that are required in the configuration will be present when the agent starts.
I've also changed the script to a restart (instead of a reload) for this same reason, i.e. any new plugins may be ignored after setup is run if the config file is merely reloaded.
should correct issue #75
=> ensure plugins are installed before config file is created and restarted

.travis.yml
Workaround for https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
=> We actually don't need sudo(8) to run CI

.travis.yml
It looks like CI's failing frequently doe to "layer does not exist". I suspect it was caused due to way too aggressive caching of Docker local files.
=> Avoid caching `/var/lib/docker` to solve Docker's layer caching issue on travis-ci.org

.kitchen.yml, .travis.yml, Berksfile, Gemfile, Gemfile.lock, attributes/default.rb, libraries/helpers.rb, metadata.rb, providers/filter.rb, providers/match.rb, providers/source.rb, recipes/install.rb, spec/spec_helper.rb, spec/unit/recipes/default_spec.rb, spec/unit/recipes/install_spec.rb, spec/unit/resources/td_agent_filter_spec.rb, spec/unit/resources/td_agent_match_spec.rb, spec/unit/resources/td_agent_source_spec.rb, templates/default/filter.conf.erb, templates/default/match.conf.erb, templates/default/source.conf.erb, test/fixtures/smoke/recipes/default.rb, test/fixtures/td-agent-spec/Berksfile, test/fixtures/td-agent-spec/README.md, test/fixtures/td-agent-spec/metadata.rb, test/fixtures/td-agent-spec/recipes/filter.rb, test/fixtures/td-agent-spec/recipes/match.rb, test/fixtures/td-agent-spec/recipes/source.rb
to @yyuu 
I have been working with this cookbook and figured I would contribute added features upstream! They are mainly to support the latest `td-agent`, and other changes to support unit and integration testing.
* Support `@type` on version 3 of td-agent in templates
* Support installation from internal/non-public repositories (artifactory, etc)
* Add unit testing support
* Modify integration test suite to successfully run
* Fix some Foodcritic offenses
Locally with Chefpsec:
```
$ rspec  spec/unit/
td-agent::default
converges without error
creates td-agent.conf
starts and enables the td-agent service
td-agent::install
converges without error
Finished in 0.87151 seconds (files took 3.09 seconds to load)
4 examples, 0 failures
```
Also ran `kitchen` locally against `3x-ubuntu14.04` …
=> Support Internal Repos, Unit Testing, @Type, 3x-, and more

recipes/configure.rb, recipes/default.rb, spec/unit/recipes/configure_spec.rb, spec/unit/recipes/default_spec.rb
to @yyuu 
resolves #110 (additional context in the issue)
* Split the resources defined in `td-agent::default` into their own recipe (this retains the previous behavior as well)
* Update unit tests
* Bump minor version
* Locally with unit tests
* Locally with Kitchen
=> [recipes] move resources from default into configure recipe

.kitchen.yml, libraries/helpers.rb, providers/filter.rb, providers/match.rb, providers/source.rb, resources/filter.rb, resources/match.rb, resources/source.rb, test/fixtures/smoke/recipes/default.rb
It looks like chef client will throw exception if a resource is declaring an attribute named `params` and `treat_deprecation_warnings_as_errors` is set.
=> The backward compatibility code for `params` keyword won't work if `treat_deprecation_warnings_as_errors` is set (fixes #112)

libraries/helpers.rb, test/fixtures/smoke/recipes/default.rb, test/integration/1x-chef12/bash/spec/localhost/lwrp_spec.rb, test/integration/2x-chef12/bash/spec/localhost/lwrp_spec.rb, test/integration/2x-chef13/bash/spec/localhost/lwrp_spec.rb
It looks like after #108, `td_agent_source` starts generating configuration string for list type parameter differently than before.
=> Add test case for list type parameters

attributes/default.rb, recipes/install.rb
Hi,
I've experienced some issue trying to install td-agent v3 on Amazon linux. I've made a fix that seems to work, but the creation of the repo url is kinda hacky as not all versions of amazon linux have an installer available. Could you take a look? Any feedback for improvement is most welcome!
(tested on serveral versions of Amazon linux 1 and 2)
=> fixed td-agent version 3 for amazon linux

providers/filter.rb, providers/match.rb, providers/plugin.rb, providers/source.rb
On why-run, these providers always detect updated resources.
We regularly execute why-run to ensure idempotency, so want to avoid 'updated_by_last_action' when not neccessary to converge.
=> suppress update resource on why-run
